import { EmailAddress } from "./EmailAddress"

class ApprovedDomains {

  private domains: string[] = [
    // host
    "winlab.rutgers.edu",
    "orbit-lab.org",

    // ONAP members
    "linuxfoundation.org",
    "amdocs.com",
    "att.com",
    "bell.ca",
    "chinamobileltd.com",
    "chinatelecom-h.com",
    "cisco.com",
    "ericsson.com",
    "gigaspaces.com",
    "huawei.com",
    "ibm.com",
    "intel.com",
    "jio.com",
    "nokia.com",
    "orange.com",
    "techmahindra.com",
    "vmware.com",
    "zte.com.co",
    "accenture.com",
    "arm.com",
    "boco.com.cn",
    "canonical.com",
    "certusnet.com",
    "chinaunicom.com",
    "ciena.ca",
    "cloudbase.it",
    "comcastcorporation.com",
    "coriant.com",
    "fujitsu.com",
    "h3c.com/portal",
    "infosys.com",
    "juniper.net",
    "mavenir.com",
    "metaswitch.com",
    "microsoft.com",
    "mirantis.com",
    "netcracker.com",
    "netsia.com",
    "pccwglobal.com",
    "raisecom.com",
    "redhat.com",
    "samsung.com",
    "vimpelcom.com",
    "windriver.com",
    "windstream.com",
    "opennetworking.org",

    // ONF members (selected)
    "att.com",
    "ciena.com",
    "cisco.com",
    "chinaunicom.com",
    // "xfinity.com",
    "telekom.com",
    "ericsson.com",
    "fujitsu.com",
    "google.com",
    "huawei.com",
    // "intel.com",
    "nec.com",
    "nokia.com",
    "ntt.com",
    // "radisys.com",
    // "samsung.com",
    // "turktelekom.com.tr",
    "verizon.com",
    // "accton.com",
    // "aricent.com",
    // "broadcom.com",
    // "biigroup.com",
    // "cavium.com",
    // "corsa.com",
    // "criterionnetworks.com",
    // "etri.re.kr",
    // "gigamon.com",
    // "ixiacom.com",
    // "mellanox.com",
    // "netronome.com",
    // "netsia.com",
    // "noviflow.com",
    // "sdnlab.com",
    "sktelecom.com",
    // "tatacommunications.com",
    // "tid.es",
    // "xilinx.com",
    "zte.com.cn",
    "advaoptical.com",
    // "alliedtelesis.com",
    // "anritsu.com",
    // "arm.com",
    // "barefootnetworks.com",
    // "suitabletech.com",
    "bisdn.de",
    // "bluecoat.com",
    // "brain4net.com",
    // "cengn.ca",
    // "cenx.com",
    "ceragon.com",
    // "caict.ac.cn",
    "chinamobileltd.com",
    "chinatelecom-h.com",
    // "cht.com.tw",
    // "cyretix.com",
    // "fabric4cloud.com",
    // "force10networks.com",
    "defense.gov",
    // "ecitele.com",
    // "extremenetworks.com",
    "facebook.com",
    // "fiberhomegroup.com",
    // "gigamon.com",
    // "business.globe.com.ph",
    // "h3c.com",
    "hcltech.com",
    // "hpe.com",
    // "web.iii.org.tw",
    // "infinera.com",
    // "inventec.com",
    // "itri.org.tw",
    "juniper.net",
    // "lenovo.com/systems",
    "microsoft.com",
    // "nephosinc.com",
    // "nep-tune.org",
    // "netbergtw.com",
    // "netscout.com",
    // "northboundnetworks.com",
    // "nxp.com",
    // "openxnet.cn",
    // "optumi.com",
    // "platinasystems.com",
    // "raisecom.com",
    // "ricoh.com",
    // "sdnessentials.com",
    // "sedonasys.com",
    "sm-optics.com",
    "swisscom.ch",
    // "telus.com",
    // "tencent.com",
    // "telecomitalia.com",
    // "tsmc.com",
    // "tta.or.kr/eng/index.jsp",
    // "velocloud.com",
    "vodafone.com",
    // "whitestack.com",
    "wipro.com",
    // "accelleran.com",
    // "aarnet.edu.au",
    // "airhopcomm-web.com",
    // "akamai.com",
    // "adaranetworks.com",
    // "adtran.com",
    // "flir.com/home",
    // "amlight.net",
    // "atto-research.com",
    // "blackducksoftware.com",
    // "broadband-forum.org",
    // "english.bupt.edu.cn",
    // "calix.com",
    // "celestica.com/Home/Home.aspx",
    // "cnit.it",
    // "create-net.fbk.eu",
    // "cobhamwireless.com",
    // "csiro.au",
    // "equinix.com",
    // "flex.com",
    // "garr.it",
    // "geant.net",
    // "happiestminds.com",
    // "ieee.org",
    // "infosys.com",
    // "inspire.edu.gr",
    // "en.inspur.com",
    // "internet2.edu",
    // "iptsolutions.ir",
    // "kaist.edu",
    // "kreonet.net",
    // "kisti.re.kr",
    // "limemicro.com",
    // "lip6.fr",
    // "lumentum.com",
    // "mef.net",
    // "microsemi.com",
    // "nctu.edu.tw",
    // "ng4t.com",
    // "openairinterface.org",
    // "openflow.co.kr",
    // "oplink.com",
    // "polito.it",
    // "postech.ac.kr",
    // "qct.io",
    // "quortus.com",
    // "sprint.com",
    // "sri.com",
    "techmahindra.com",
    "ubuntu.com",
    // "i2t.ehu.eus",
    // "cs.utah.edu",
    // "en.ustc.edu.cn",
    // "us-ignite.org",
    // "viavisolutions.com",
    // "villa-technologies.com",
    // "windstream.com",
    // "xpose.com",
    // "xran.org",

    // volunteers
    "frinx.io",
    "highstreet-technologies.com"
  ];

  isApproved(s: string) {

    let email = new EmailAddress(s)
    let test = s
    
    if (email.isEmail()) {
      test = email.domain()
    }
    
    return this.domains.some(item => item === test)
  }
}
export { ApprovedDomains };

